events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://host-app:80/;
            proxy_set_header Host $host;
        }

        location /browse {
            rewrite ^/browse(.*)$ /$1 break;
            proxy_pass http://browse-app:80/;
            proxy_set_header Host $host;
        }

        location /settings {
            rewrite ^/settings(.*)$ /$1 break;
            proxy_pass http://settings-app:80/;
            proxy_set_header Host $host;
        }

        location /watchlist {
            rewrite ^/watchlist(.*)$ /$1 break;
            proxy_pass http://watchlist-app:80/;
            proxy_set_header Host $host;
        }
    }
}
